### ISSUE TITLE
Config file parsing issue

### ISSUE THREAD

**Issue by SergioGasquez** [esp-rs/espflash#383]
Since `toml` crate was updated, parsing a file like: 
```toml
[connection]

[[usb_device]]
vid = "303a"
pid = "1001"
```

Results in: 
```
Error:
  × TOML parse error at line 4, column 7
  │   |
  │ 4 | vid = "303a"
  │   |       ^^^^^^
  │ invalid type: string "303a", expected a borrowed byte array
  │
```
See #374 #381 for details
